### ISSUE TITLE
goreader: command not found

### ISSUE THREAD

**Issue by 1094** [taylorskalyo/goreader#5]
I have never used `go` before, but I have been looking for a good (and maintained) terminal epub reader for a while. 

I installed `go` and then I followed the directions in the read me, but either `bash` or `zsh` can find the program. Can you help me figure out what I'm missing?

**Comment by taylorskalyo** [comment]
This doesn't sound like an issue with goreader specifically, but I'm happy to help regardless. I think what's happening is that the directory `go` uses to store binaries (`$HOME/go/bin` by default) hasn't been added to your `PATH` environment variable. I would try adding the following to your `.bashrc` or `.zshrc` file:

```sh
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
```

https://stackoverflow.com/questions/36083542/error-command-not-found-with-golang
https://wiki.archlinux.org/index.php/Go#.24GOPATH

**Comment by 1094** [comment]
I wasn't sure where to start looking and my search hadn't returned that Stackoverflow question, so thank you for taking the time to assist. That fixed the problem.

And that I can play with it, I can see that it's awesome and will get a lot of use.  Thanks so much for sharing it.
